import React, { useState, useEffect } from 'react';
import { MdAdd, MdDelete, MdSave, MdInfo, MdRefresh, MdCheckCircle, MdCancel, MdEdit } from 'react-icons/md';
import { api } from '../../api';

function CustomerSegments({ scope }) {
  // Config state (bp_customer_segment_config)
  const [segmentsEnabled, setSegmentsEnabled] = useState(false);
  const [defaultSegmentId, setDefaultSegmentId] = useState(null);
  
  // Segments state (bp_customer_segment_master)
  const [segments, setSegments] = useState([]);
  const [originalData, setOriginalData] = useState({ enabled: false, defaultId: null, segments: [] });
  
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState(null);
  const [successMessage, setSuccessMessage] = useState('');
  const [schema, setSchema] = useState('base_pricing'); // Dynamic schema
  
  // Tooltip state
  const [showTooltip, setShowTooltip] = useState(false);
  const [showDisplayTooltip, setShowDisplayTooltip] = useState(false);
  
  // Label edit mode - enabled by clicking pencil in header
  const [labelEditMode, setLabelEditMode] = useState(false);
  
  // Setup mode - when resetting, ask for segment count
  const [setupMode, setSetupMode] = useState(false);
  const [segmentCount, setSegmentCount] = useState(5);

  // Fetch data from bp_customer_segment_config and bp_customer_segment_master
  useEffect(() => {
    fetchData();
  }, []);

  const fetchData = async () => {
    try {
      setLoading(true);
      setError(null);
      
      // Fetch connection status to get schema
      try {
        const connectionStatus = await api.getConnectionStatus();
        if (connectionStatus.data.schema) {
          setSchema(connectionStatus.data.schema);
        }
      } catch (e) {
        console.log('Could not fetch schema from connection status');
      }
      
      const response = await api.getCustomerSegments();
      // api.getCustomerSegments returns { config: {...}, segments: [...] }
      const enabled = response.config?.is_customer_segment_enabled || false;
      const defaultId = response.config?.default_segment_id || null;
      const segs = response.segments || [];
      
      setSegmentsEnabled(enabled);
      setDefaultSegmentId(defaultId);
      setSegments(segs);
      setOriginalData({ enabled, defaultId, segments: JSON.parse(JSON.stringify(segs)) });
    } catch (err) {
      console.error('Failed to fetch customer segments:', err);
      // Set defaults on error
      setSegmentsEnabled(false);
      setSegments([]);
    } finally {
      setLoading(false);
    }
  };

  const handleAddSegment = () => {
    const newId = segments.length > 0 ? Math.max(...segments.map(s => s.segment_id)) + 1 : 10001;
    setSegments([...segments, {
      segment_id: newId,
      segment_code: '',
      segment_name: '',
      is_active: true
    }]);
  };

  const handleDeleteSegment = (id) => {
    setSegments(segments.filter(s => s.segment_id !== id));
    // Clear default if deleted
    if (defaultSegmentId === id) {
      setDefaultSegmentId(null);
    }
  };

  // Standardize display name: replace underscores with spaces, trim, preserve caps
  const formatDisplayName = (value) => {
    return value
      .replace(/_/g, ' ')      // Replace underscores with spaces
      .replace(/\s+/g, ' ')    // Replace multiple spaces with single space
      .trim();
  };

  // Generate label from display name: lowercase, spaces to underscores
  const generateLabel = (displayName) => {
    return displayName.toLowerCase().replace(/\s+/g, '_').trim();
  };

  // Handle display name change (segment_name)
  const handleDisplayChange = (index, value) => {
    const updated = [...segments];
    const currentLabel = updated[index].segment_code || '';
    const currentDisplay = updated[index].segment_name || '';
    
    updated[index].segment_name = value;
    
    // Only auto-update label if it's empty or matches the auto-generated version
    const wasAutoGenerated = !currentLabel || currentLabel === generateLabel(formatDisplayName(currentDisplay));
    if (wasAutoGenerated && value.trim()) {
      updated[index].segment_code = generateLabel(formatDisplayName(value));
    }
    
    setSegments(updated);
  };

  // Handle label change (segment_code)
  const handleLabelChange = (index, value) => {
    const updated = [...segments];
    updated[index].segment_code = value;
    setSegments(updated);
  };

  const handleSave = async () => {
    // Validate all display names are filled
    const emptyValues = segments.filter(s => !s.segment_name?.trim());
    if (emptyValues.length > 0) {
      setError('Please fill in all segment display names before saving');
      return;
    }

    try {
      setSaving(true);
      setError(null);
      
      // Format display names and generate labels only if not already set
      const segmentsToSave = segments.map(segment => ({
        ...segment,
        segment_name: formatDisplayName(segment.segment_name),
        segment_code: segment.segment_code?.trim() || generateLabel(segment.segment_name)
      }));

      await api.saveCustomerSegments({
        config: {
          is_customer_segment_enabled: segmentsEnabled,
          default_segment_id: defaultSegmentId
        },
        segments: segmentsToSave
      });
      setSuccessMessage('Customer segment configuration saved successfully!');
      setTimeout(() => setSuccessMessage(''), 3000);
      fetchData();
    } catch (err) {
      console.error('Failed to save:', err);
      setError('Failed to save changes: ' + (err.response?.data?.detail || err.message));
    } finally {
      setSaving(false);
    }
  };

  const updateSegment = (index, field, value) => {
    const updated = [...segments];
    updated[index][field] = value;
    setSegments(updated);
  };

  // Generate empty segments based on count
  const generateSegments = () => {
    setError(null);
    const newSegments = [];
    for (let i = 0; i < segmentCount; i++) {
      newSegments.push({
        segment_id: 10001 + i,
        segment_code: '',
        segment_name: '',
        is_active: true
      });
    }
    setSegments(newSegments);
    setDefaultSegmentId(10001); // First segment is default
    setSetupMode(false);
  };

  if (loading) {
    return (
      <div style={{ textAlign: 'center', padding: '40px', color: '#6b7280' }}>
        Loading customer segments...
      </div>
    );
  }

  // Setup mode - ask for count
  if (setupMode) {
    return (
      <div>
        <div style={{
          background: '#f8fafc',
          border: '1px solid #e2e8f0',
          borderRadius: '12px',
          padding: '32px',
          textAlign: 'center',
          maxWidth: '500px',
          margin: '0 auto'
        }}>
          <h3 style={{ margin: '0 0 8px 0', color: '#1a1a2e', fontSize: '18px' }}>
            Setup Customer Segments
          </h3>
          <p style={{ color: '#64748b', fontSize: '14px', marginBottom: '24px' }}>
            How many customer segments do you want to configure?
          </p>
          
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '12px', marginBottom: '24px' }}>
            <input
              type="number"
              min="1"
              max="20"
              value={segmentCount}
              onChange={(e) => setSegmentCount(Math.min(20, Math.max(1, parseInt(e.target.value) || 1)))}
              style={{
                width: '80px',
                padding: '12px',
                fontSize: '18px',
                textAlign: 'center',
                borderRadius: '8px',
                border: '1px solid #d0d0d0',
                outline: 'none'
              }}
            />
            <span style={{ color: '#6b7280', fontSize: '14px' }}>segments</span>
          </div>
          
          <div style={{ display: 'flex', gap: '12px', justifyContent: 'center' }}>
            <button
              onClick={() => setSetupMode(false)}
              style={{
                ...secondaryButtonStyle,
                padding: '12px 24px',
                fontSize: '15px'
              }}
            >
              Cancel
            </button>
            <button
              onClick={generateSegments}
              style={{
                ...saveButtonStyle,
                padding: '12px 32px',
                fontSize: '15px'
              }}
            >
              Generate Segments
            </button>
          </div>
          
          <p style={{ fontSize: '12px', color: '#9ca3af', marginTop: '16px' }}>
            You can add or remove segments later
          </p>
        </div>
      </div>
    );
  }

  const activeSegmentsCount = segments.filter(s => s.is_active).length;
  
  // Check if there are unsaved changes
  const hasChanges = segmentsEnabled !== originalData.enabled 
    || defaultSegmentId !== originalData.defaultId 
    || JSON.stringify(segments) !== JSON.stringify(originalData.segments);

  return (
    <div>
      {/* Status Summary Card - Green/Red based on enabled */}
      <div style={{
        display: 'flex',
        alignItems: 'center',
        gap: '16px',
        padding: '16px 20px',
        background: segmentsEnabled ? '#f0fdf4' : '#fef2f2',
        borderRadius: '10px',
        border: `1px solid ${segmentsEnabled ? '#86efac' : '#fecaca'}`,
        marginBottom: '16px'
      }}>
        {segmentsEnabled ? (
          <MdCheckCircle size={24} style={{ color: '#22c55e' }} />
        ) : (
          <MdCancel size={24} style={{ color: '#ef4444' }} />
        )}
        <div style={{ flex: 1, display: 'flex', alignItems: 'center', gap: '8px' }}>
          <span style={{ fontWeight: '600', color: segmentsEnabled ? '#166534' : '#991b1b', fontSize: '15px' }}>
            Customer Segments: {segmentsEnabled ? 'ENABLED' : 'DISABLED'}
          </span>
          {segmentsEnabled && (
            <div style={{ position: 'relative', display: 'inline-flex' }}>
              <MdInfo 
                size={16} 
                style={{ color: '#15803d', cursor: 'pointer' }}
                onMouseEnter={() => setShowTooltip(true)}
                onMouseLeave={() => setShowTooltip(false)}
              />
              {showTooltip && (
                <div style={{
                  position: 'absolute',
                  top: '100%',
                  left: '50%',
                  transform: 'translateX(-50%)',
                  marginTop: '8px',
                  padding: '10px 14px',
                  background: '#1e293b',
                  color: '#fff',
                  borderRadius: '6px',
                  fontSize: '12px',
                  whiteSpace: 'nowrap',
                  zIndex: 100,
                  boxShadow: '0 4px 12px rgba(0,0,0,0.15)'
                }}>
                  Define customer segments for price differentiation. Mark one segment as Default for use when no specific segment is selected.
                </div>
              )}
            </div>
          )}
        </div>
        <label style={{
          display: 'flex',
          alignItems: 'center',
          gap: '12px',
          cursor: 'pointer'
        }}>
          <span style={{ 
            fontSize: '14px', 
            fontWeight: '500',
            color: segmentsEnabled ? '#16a34a' : '#6b7280'
          }}>
            {segmentsEnabled ? 'ON' : 'OFF'}
          </span>
          <div style={{
            position: 'relative',
            width: '52px',
            height: '28px'
          }}>
            <input
              type="checkbox"
              checked={segmentsEnabled}
              onChange={(e) => setSegmentsEnabled(e.target.checked)}
              style={{
                position: 'absolute',
                opacity: 0,
                width: '100%',
                height: '100%',
                cursor: 'pointer',
                zIndex: 1
              }}
            />
            <div style={{
              position: 'absolute',
              inset: 0,
              background: segmentsEnabled ? '#22c55e' : '#d1d5db',
              borderRadius: '14px',
              transition: 'background 0.2s'
            }} />
            <div style={{
              position: 'absolute',
              top: '4px',
              left: segmentsEnabled ? '28px' : '4px',
              width: '20px',
              height: '20px',
              background: '#fff',
              borderRadius: '50%',
              boxShadow: '0 1px 3px rgba(0,0,0,0.2)',
              transition: 'left 0.2s'
            }} />
          </div>
        </label>
      </div>

      {/* Compact Header - Impact UI Style */}
      <div style={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: '12px 20px',
        background: 'white',
        borderRadius: '10px',
        border: '1px solid #e2e8f0',
        marginBottom: '16px',
        boxShadow: '0 1px 3px rgba(0,0,0,0.04)'
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
          <MdCheckCircle size={20} style={{ color: '#22c55e' }} />
          <span style={{ fontWeight: '500', color: '#1a1a2e', fontSize: '15px' }}>
            {segments.length} Segment{segments.length !== 1 ? 's' : ''}
          </span>
          <span style={{ color: '#94a3b8' }}>·</span>
          <code style={{ 
            fontSize: '13px', 
            color: '#64748b',
            background: '#f1f5f9',
            padding: '4px 8px',
            borderRadius: '4px'
          }}>
            {schema}.bp_customer_segment_master
          </code>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
          <button style={iconButtonStyle} onClick={fetchData} title="Refresh">
            <MdRefresh size={18} />
          </button>
          <button style={secondaryButtonStyle} onClick={handleAddSegment}>
            <MdAdd size={16} style={{ marginRight: '4px' }} />
            Add Segment
          </button>
          {hasChanges && (
            <>
              <button 
                style={discardButtonStyle} 
                onClick={() => {
                  setSegmentsEnabled(originalData.enabled);
                  setDefaultSegmentId(originalData.defaultId);
                  setSegments(JSON.parse(JSON.stringify(originalData.segments)));
                  setError(null);
                }}
              >
                Discard
              </button>
              <button style={saveButtonStyle} onClick={handleSave} disabled={saving}>
                <MdSave size={16} style={{ marginRight: '4px' }} />
                {saving ? 'Saving...' : 'Save'}
              </button>
            </>
          )}
          <button
            onClick={() => setSetupMode(true)}
            style={resetButtonStyle}
            title="Reset and reconfigure"
          >
            Reset
          </button>
        </div>
      </div>

      {successMessage && (
        <div style={{ padding: '12px', background: '#f0fdf4', border: '1px solid #86efac', borderRadius: '8px', color: '#166534', marginBottom: '16px', fontSize: '14px' }}>
          {successMessage}
        </div>
      )}

      {error && (
        <div style={{ padding: '12px', background: '#fef2f2', border: '1px solid #fecaca', borderRadius: '8px', color: '#dc2626', marginBottom: '16px', fontSize: '14px' }}>
          {error}
        </div>
      )}

      {/* Segments Configuration - Only show when enabled */}
      {segmentsEnabled && (
        <>
          {/* Segments Table */}
          <div style={{ border: '1px solid #e0e0e0', borderRadius: '8px', overflow: 'hidden' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse' }}>
              <thead>
                <tr style={{ background: '#f5f5f5' }}>
                  <th style={{ ...thStyle, width: '70px' }}>ID</th>
                  <th style={thStyle}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
                      Segment Display
                      <div style={{ position: 'relative', display: 'inline-flex' }}>
                        <MdInfo 
                          size={14} 
                          style={{ color: '#9ca3af', cursor: 'pointer' }}
                          onMouseEnter={() => setShowDisplayTooltip(true)}
                          onMouseLeave={() => setShowDisplayTooltip(false)}
                        />
                        {showDisplayTooltip && (
                          <div style={{
                            position: 'absolute',
                            top: '100%',
                            left: '50%',
                            transform: 'translateX(-50%)',
                            marginTop: '8px',
                            padding: '10px 12px',
                            background: '#1a1a2e',
                            color: '#fff',
                            fontSize: '12px',
                            borderRadius: '6px',
                            width: '280px',
                            zIndex: 100,
                            lineHeight: '1.5',
                            boxShadow: '0 4px 12px rgba(0,0,0,0.15)'
                          }}>
                            On save: underscores (_) are replaced with spaces and extra spaces are trimmed. Capitalization is preserved (e.g., Residential stays Residential, Residential_Segment → Residential Segment).
                            <div style={{
                              position: 'absolute',
                              top: '-6px',
                              left: '50%',
                              transform: 'translateX(-50%)',
                              width: 0,
                              height: 0,
                              borderLeft: '6px solid transparent',
                              borderRight: '6px solid transparent',
                              borderBottom: '6px solid #1a1a2e'
                            }} />
                          </div>
                        )}
                      </div>
                    </div>
                  </th>
                  <th style={thStyle}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
                      Segment Label
                      <MdEdit 
                        size={14} 
                        style={{ 
                          color: labelEditMode ? '#264CD7' : '#9ca3af', 
                          cursor: 'pointer',
                          transition: 'color 0.2s'
                        }}
                        onClick={() => setLabelEditMode(!labelEditMode)}
                        title={labelEditMode ? "Click to lock labels" : "Click to edit labels"}
                      />
                    </div>
                  </th>
                  <th style={{ ...thStyle, width: '80px', textAlign: 'center' }}>Active</th>
                  <th style={{ ...thStyle, width: '80px', textAlign: 'center' }}>Default</th>
                  <th style={{ ...thStyle, width: '70px', textAlign: 'center' }}></th>
                </tr>
              </thead>
              <tbody>
                {segments.length === 0 ? (
                  <tr>
                    <td colSpan={6} style={{ padding: '32px', textAlign: 'center', color: '#6b7280' }}>
                      No segments configured. Click "Add Segment" to create one.
                    </td>
                  </tr>
                ) : (
                  segments.map((segment, index) => (
                    <tr key={segment.segment_id} style={{ borderBottom: '1px solid #e0e0e0' }}>
                      <td style={{ ...tdStyle, textAlign: 'center', fontWeight: '500', color: '#6b7280', fontFamily: 'monospace' }}>
                        {segment.segment_id}
                      </td>
                      <td style={tdStyle}>
                        <input
                          type="text"
                          value={segment.segment_name || ''}
                          onChange={(e) => handleDisplayChange(index, e.target.value)}
                          style={inputStyle}
                          placeholder="e.g., Residential"
                        />
                      </td>
                      <td style={tdStyle}>
                        {labelEditMode ? (
                          <input
                            type="text"
                            value={segment.segment_code || ''}
                            onChange={(e) => handleLabelChange(index, e.target.value)}
                            style={inputStyle}
                            placeholder="e.g., residential"
                          />
                        ) : (
                          <span style={{ 
                            padding: '8px 12px', 
                            display: 'block',
                            color: segment.segment_code ? '#374151' : '#9ca3af',
                            fontFamily: 'monospace',
                            fontSize: '13px'
                          }}>
                            {segment.segment_code || '(auto-generated)'}
                          </span>
                        )}
                      </td>
                      <td style={{ ...tdStyle, textAlign: 'center' }}>
                        <input
                          type="checkbox"
                          checked={segment.is_active || false}
                          onChange={(e) => updateSegment(index, 'is_active', e.target.checked)}
                          style={{ width: '18px', height: '18px', cursor: 'pointer' }}
                        />
                      </td>
                      <td style={{ ...tdStyle, textAlign: 'center' }}>
                        <input
                          type="radio"
                          name="defaultSegment"
                          checked={defaultSegmentId === segment.segment_id}
                          onChange={() => setDefaultSegmentId(segment.segment_id)}
                          style={{ width: '18px', height: '18px', cursor: 'pointer' }}
                        />
                      </td>
                      <td style={{ ...tdStyle, textAlign: 'center' }}>
                        <button 
                          style={{
                            ...deleteButtonStyle,
                            opacity: defaultSegmentId === segment.segment_id ? 0.3 : 1
                          }}
                          onClick={() => handleDeleteSegment(segment.segment_id)}
                          disabled={defaultSegmentId === segment.segment_id}
                          title={defaultSegmentId === segment.segment_id ? "Can't delete default segment" : "Delete segment"}
                        >
                          <MdDelete />
                        </button>
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </>
      )}
    </div>
  );
}

const thStyle = { padding: '12px 16px', textAlign: 'left', fontWeight: '600', fontSize: '13px', color: '#374151' };
const tdStyle = { padding: '10px 16px', fontSize: '14px', color: '#333' };
const inputStyle = { width: '100%', minWidth: '140px', padding: '8px 12px', borderRadius: '6px', border: '1px solid #d0d0d0', fontSize: '14px', boxSizing: 'border-box' };
const iconButtonStyle = { display: 'flex', alignItems: 'center', justifyContent: 'center', width: '36px', height: '36px', borderRadius: '8px', border: '1px solid #e2e8f0', background: '#fff', cursor: 'pointer', color: '#64748b' };
const secondaryButtonStyle = { display: 'flex', alignItems: 'center', padding: '8px 14px', borderRadius: '8px', border: '1px solid #e2e8f0', background: '#fff', cursor: 'pointer', fontSize: '13px', fontWeight: '500', color: '#374151' };
const saveButtonStyle = { display: 'flex', alignItems: 'center', padding: '8px 16px', borderRadius: '6px', border: 'none', background: '#264CD7', color: '#fff', cursor: 'pointer', fontSize: '14px', fontWeight: '500' };
const discardButtonStyle = { display: 'flex', alignItems: 'center', padding: '8px 16px', borderRadius: '6px', border: '1px solid #d0d0d0', background: '#fff', color: '#374151', cursor: 'pointer', fontSize: '14px', fontWeight: '500' };
const resetButtonStyle = { display: 'flex', alignItems: 'center', padding: '8px 14px', borderRadius: '6px', border: '1px solid #e2e8f0', background: '#f8fafc', color: '#64748b', cursor: 'pointer', fontSize: '13px', fontWeight: '500' };
const deleteButtonStyle = { display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '8px', borderRadius: '6px', border: 'none', background: 'transparent', color: '#dc2626', cursor: 'pointer', fontSize: '18px' };

export default CustomerSegments;
